---
- name: install Nginx
  apt: 
    name: nginx
    state: present

- name: copy conf file
  template:
    src: deb_nginx.conf
    dest: /etc/nginx/sites-available
  notify: Restart nginx

- name: Enable New site
  command: /usr/sbin/a2ensite deb_nginx.conf
  notify: Restart nginx

- name: Disable default page
  command: /usr/sbin/a2dissite 000-default.conf
  notify: Restart nginx

- name: Nginx start at boot time
  service:
    name: nginx
    state: started
    enabled: yes