---
- name: install apache and other modules
  apt:
    name:
      - apache2
      - libxml2-dev
    state: present

- name: Enabling the modules
  command:
    argv:
      - a2enmod rewrite
      - a2enmod proxy
      - a2enmod proxy_balancer
      - a2enmod proxy_http
      - a2enmod headers
      - a2enmod lbmethod_bytraffic
  notify: Restart apache2

- name: copy conf file
  templates:
    src: debian_apache.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart apache2

- name: Enable apache
  service:
    name: apache2
    state: started
    enabled: yes
